### PR TITLE
PeridexisErrant's updates

### PR DESCRIPTION
**Pull request by PeridexisErrant**
I think that my build scripts ([here](https://github.com/PeridexisErrant/starter-pack)) are sufficiently powerful that my base probably _shouldn't_ merge with the shared core... but I'd still like them to be close enough to easily swap between them.

So here's a couple of commits worth of my changes, for review by other users (@lethosor, @carterscottm) before merging.  The focus here is on removing redundant, obsolete, or surplus stuff.

### CODE REVIEW

**Comment by lethosor** [comment]
One reason for the travis script, from what I remember, was that some keybindings actually *were* missing keys. It's probably less likely to happen now with the minimal keybinding format, but it can't hurt.

Also, I just patched the script so it doesn't fail with the new keybinding format, and it looks like your branch contains that change too. Was it just the "0 keybindings found" message that you thought was the issue?

**Comment by carterscottm** [comment]
I'm definitely no authority on this, but it looks good to me.  You found a few things that I overlooked in #15.  I didn't realize that the enabled tag wasn't necessary, for instance.

**Comment by PeridexisErrant** [comment]
@lethosor Oops, hadn't noticed the patched script.  Nice work!

@carterscottm I only noticed myself a few days ago - PyLNP does use the enabled state internally, but never reads it from this file!  So I've opened an issue to stop saving out config that never gets read in, because that *is* misleading.  (I actually had a few set to `true`, and when I realised I had to write a script to actually enable them...)  In general, PyLNP is pretty robust about using auto detection and defaults when config is missing.

**Comment by carterscottm** [comment]
I have incorporated the changes from this PR into #18.  Closing this PR per @PeridexisErrant's request.

**Pull request closed without merging**
